### PR TITLE
Relax phoenix_live_view version contraint

### PR DESCRIPTION
**Pull request by wkirschbaum**
I tested this on phoenix_live_view 0.20 and works as expected

### CODE REVIEW

**Comment by DianaOlympos** [comment]
is there a reason for this change? What is it impacting ?

**Comment by wkirschbaum** [comment]
@DianaOlympos its impacting the ability install with live_view 0.20 which is the current version of live_view.

**Comment by DianaOlympos** [comment]
I will release a new version as soon as i get back to a computer today

**Comment by wkirschbaum** [comment]
Sorry, i should have had a better description. Thanks, but no stress on my side, we are using the fork for now.

**Comment by John-Goff** [comment]
Hey @DianaOlympos sorry for the tag but any chance we could get a release? The version on hex.pm is still unable to be used with liveview 0.20. Thanks in advance! :)

**Comment by DianaOlympos** [comment]
You are totally right. Life happened. I will do a release tomorrow. Ping me next week if it is not done

**Comment by DianaOlympos** [comment]
Should be done as v1.0.4!

https://hex.pm/packages/orion

Thank you for the reminder and for the patch.

**Pull request merged**
